-- AlterTable
ALTER TABLE "Voice" ADD COLUMN     "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "gigId" INTEGER,
ALTER COLUMN "bandId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Voice" ADD CONSTRAINT "Voice_gigId_fkey" FOREIGN KEY ("gigId") REFERENCES "Gig"("id") ON DELETE CASCADE ON UPDATE CASCADE;
